packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  esbuild: true
  prisma: true

catalog:
  "eslint": "10.9.1"
  "typescript": "^5.9.2"
  "dotenv": "^17.0.0"
  "vitest": "^3.2.7"
  "@types/node": "^22.0.0"
